spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: auth-server
        uri: http://localhost:8181/
        predicates:
          - Path=/token
      - id: tweets
        uri: http://localhost:8081/
        predicates:
          - Path=/api/v1/tweet
      - id: tweets-following
        uri: http://localhost:8081/
        predicates:
          - Path=/api/v1/following
      - id: feeds
        uri: http://localhost:8082/
        predicates:
          - Path=/api/v1/feeds**
